project:
  type: website
  output-dir: "docs"

website:
  navbar:
    background: primary
    title: "PECE Lab"
    right:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html

format:
  html:
    theme: flatly
    css: "css/custom.css"
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
    highlight: tango
    lib_dir: libs



